[package]
name = "flualogger"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1"
chrono = { version = "0.4", features = ["clock"] }
dirs-next = "2.0"

[dev-dependencies]
tempfile = "3"
