[package]
name = "fluaoslib"
version = "0.1.0"
edition = "2024"

[dependencies]
rfd = "0.15.4"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.1", features = ["Win32_System_Console"] }
